apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: microservice-canary
  labels:
    app: microservice
    component: configuration
    environment: production
data:
  # Environment type
  ENVIRONMENT: "production"
  CLUSTER_TYPE: "kubernetes"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "false"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_PYTHON_LOG_LEVEL: "warn"
  OTEL_RESOURCE_ATTRIBUTES_BASE: "environment=production,cluster=k8s"
  
  # Service Configuration
  SERVICE_PORT: "5000"
  LOG_LEVEL: "warn"
  
  # SLO Simulation Defaults (production should be more conservative)
  SIM_BAD_DEFAULT: "false"
  ERROR_RATE_DEFAULT: "0.05"
  LATENCY_SIMULATION_DEFAULT: "false"
  MAX_LATENCY_DEFAULT: "1.0"
  OUTAGE_SIMULATION_DEFAULT: "false"
  
  # Load Balancer Configuration
  SERVICE_TYPE: "LoadBalancer"  # For production
  
  # Resource Limits (production)
  MEMORY_REQUEST: "256Mi"
  MEMORY_LIMIT: "512Mi"
  CPU_REQUEST: "200m"
  CPU_LIMIT: "500m"
