apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: microservice-canary
  labels:
    app: microservice
    component: configuration
    environment: local
data:
  # Environment type
  ENVIRONMENT: "local"
  CLUSTER_TYPE: "minikube"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_PYTHON_LOG_LEVEL: "info"
  OTEL_RESOURCE_ATTRIBUTES_BASE: "environment=local,cluster=minikube"
  
  # Service Configuration
  SERVICE_PORT: "5000"
  LOG_LEVEL: "info"
  
  # SLO Simulation Defaults (can be overridden per deployment)
  SIM_BAD_DEFAULT: "false"
  ERROR_RATE_DEFAULT: "0.1"
  LATENCY_SIMULATION_DEFAULT: "false"
  MAX_LATENCY_DEFAULT: "1.5"
  OUTAGE_SIMULATION_DEFAULT: "false"
  
  # Load Balancer Configuration
  SERVICE_TYPE: "NodePort"  # For minikube
  
  # Resource Limits (local/dev)
  MEMORY_REQUEST: "64Mi"
  MEMORY_LIMIT: "128Mi"
  CPU_REQUEST: "50m"
  CPU_LIMIT: "100m"
